[package]
name = "cmli-proc-macro"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = "1.0.103"
proc_macro-deterministic-rand = { git = "https://github.com/chorman0773/proc_macro-deterministic-rand", version = "0.1.0" }

[lib]
proc-macro = true
